---
- name: Setup Zsh with powerlevel10k config
  hosts: localhost
  vars:
    repo_url: "https://github.com/pulkit4603/ansible-zsh-dot.git"
    user_home: "{{ ansible_env.HOME }}"
    dotfiles_dir: "{{ ansible_env.HOME }}/.dotfiles"
    target_user: "{{ ansible_env.USER }}"
  tasks:
    - name: Install required packages (Debian/Ubuntu)
      become: yes
      apt:
        name:
          - zsh
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages (RedHat/CentOS/Fedora)
      become: yes
      package:
        name:
          - zsh
          - git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Get zsh path
      command: which zsh
      register: zsh_path
      changed_when: false

    - name: Clone dotfiles repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dotfiles_dir }}"
        version: main
        force: yes

    - name: Backup existing .zshrc if present
      command: mv "{{ user_home }}/.zshrc" "{{ user_home }}/.zshrc.bak"
      args:
        removes: "{{ user_home }}/.zshrc"
      ignore_errors: yes

    - name: Backup existing .p10k.zsh if present
      command: mv "{{ user_home }}/.p10k.zsh" "{{ user_home }}/.p10k.zsh.bak"
      args:
        removes: "{{ user_home }}/.p10k.zsh"
      ignore_errors: yes

    - name: Link .zshrc
      file:
        src: "{{ dotfiles_dir }}/.zshrc"
        dest: "{{ user_home }}/.zshrc"
        state: link
        force: yes

    - name: Link .p10k.zsh
      file:
        src: "{{ dotfiles_dir }}/.p10k.zsh"
        dest: "{{ user_home }}/.p10k.zsh"
        state: link
        force: yes

    - name: Change default shell to zsh
      become: yes
      user:
        name: "{{ target_user }}"
        shell: "{{ zsh_path.stdout }}"

    - name: Display completion message
      debug:
        msg: "Zsh setup complete! Please log out and log back in, or run 'exec zsh' to start using your new shell."
